// 웹디자인개발기능사 문제은행
// 각 conceptId는 동일 개념의 변형 문제끼리 묶어주는 키
// 학생이 같은 개념을 여러 형태의 문제로 반복 학습할 수 있도록 설계
const QUESTIONS = [
  // ===== 색채/디자인일반 =====
  { id: 1, conceptId: "rgb-additive", category: "색채/디자인일반",
    question: "빛의 3원색(RGB)을 모두 합쳤을 때 나타나는 색은? (가산혼합)",
    options: ["검정", "흰색", "회색", "노랑"], answer: 1,
    explain: "RGB는 더할수록 밝아지는 가산혼합으로, 세 색을 모두 합치면 백색이 된다." },
  { id: 101, conceptId: "rgb-additive", category: "색채/디자인일반",
    question: "다음 중 가산혼합(빛의 혼합)에 해당하는 3원색의 조합은?",
    options: ["빨강·노랑·파랑", "빨강·초록·파랑", "사이안·마젠타·노랑", "검정·흰색·회색"], answer: 1,
    explain: "빛의 3원색은 Red·Green·Blue. 모두 더하면 흰색이 된다." },
  { id: 102, conceptId: "rgb-additive", category: "색채/디자인일반",
    question: "프린터 잉크처럼 색을 섞을수록 어두워지는 혼합 방식은?",
    options: ["가산혼합", "감산혼합", "중간혼합", "병치혼합"], answer: 1,
    explain: "CMYK처럼 물감·잉크는 섞을수록 빛이 흡수되어 어두워지는 감산혼합이다." },

  { id: 2, conceptId: "color-attr", category: "색채/디자인일반",
    question: "색의 3속성에 해당하지 않는 것은?",
    options: ["색상(Hue)", "명도(Value)", "채도(Chroma)", "보색"], answer: 3,
    explain: "색의 3속성은 색상·명도·채도이며, 보색은 색상환에서 마주보는 색 관계다." },
  { id: 201, conceptId: "color-attr", category: "색채/디자인일반",
    question: "다음 중 색의 밝고 어두운 정도를 나타내는 속성은?",
    options: ["색상", "명도", "채도", "톤"], answer: 1,
    explain: "명도(Value/Lightness)는 밝기를 의미. 색상은 색의 종류, 채도는 선명함이다." },
  { id: 202, conceptId: "color-attr", category: "색채/디자인일반",
    question: "색의 선명한 정도, 즉 색의 맑고 탁한 정도를 나타내는 것은?",
    options: ["색상", "명도", "채도", "보색"], answer: 2,
    explain: "채도(Chroma/Saturation)는 색의 순수함·선명함. 회색이 섞일수록 채도가 낮아진다." },

  { id: 3, conceptId: "munsell", category: "색채/디자인일반",
    question: "먼셀 표색계에서 색을 표기하는 순서로 옳은 것은?",
    options: ["명도 채도 색상", "색상 명도/채도", "채도 색상 명도", "색상 채도/명도"], answer: 1,
    explain: "먼셀 표기는 'H V/C'(색상 명도/채도) 순. 예) 5R 4/14." },
  { id: 301, conceptId: "munsell", category: "색채/디자인일반",
    question: "먼셀 표기 '5R 4/14'에서 숫자 '14'가 의미하는 것은?",
    options: ["색상", "명도", "채도", "톤"], answer: 2,
    explain: "5R(색상) 4(명도)/14(채도). 슬래시 뒤 숫자가 채도이며 클수록 선명하다." },

  { id: 4, conceptId: "contrast", category: "색채/디자인일반",
    question: "두 보색을 인접시켰을 때 서로의 채도가 더 선명해 보이는 대비는?",
    options: ["명도대비", "계시대비", "보색대비", "연변대비"], answer: 2,
    explain: "보색을 나란히 두면 서로의 채도가 강조되는 보색대비가 나타난다." },
  { id: 401, conceptId: "contrast", category: "색채/디자인일반",
    question: "어떤 색을 한참 본 뒤 흰 종이로 시선을 옮기면 보색의 잔상이 보이는 현상은?",
    options: ["동시대비", "계시대비", "면적대비", "보색대비"], answer: 1,
    explain: "시간 차를 두고 일어나는 잔상 현상은 계시대비. 동시대비는 동시에 보일 때." },

  { id: 5, conceptId: "gestalt", category: "색채/디자인일반",
    question: "게슈탈트(Gestalt) 시지각 원리에 해당하지 않는 것은?",
    options: ["근접성", "유사성", "폐쇄성", "황금비"], answer: 3,
    explain: "게슈탈트 원리는 근접성·유사성·연속성·폐쇄성 등. 황금비는 비례 개념." },
  { id: 501, conceptId: "gestalt", category: "색채/디자인일반",
    question: "흩어진 점이라도 가까이 있는 것끼리 한 그룹으로 인식하는 게슈탈트 원리는?",
    options: ["유사성", "근접성", "연속성", "폐쇄성"], answer: 1,
    explain: "가까운 것끼리 묶어 인식하는 것은 근접성(Proximity)." },

  { id: 6, conceptId: "form-element", category: "색채/디자인일반",
    question: "형태를 이루는 가장 기본적인 조형요소가 아닌 것은?",
    options: ["점", "선", "면", "리듬"], answer: 3,
    explain: "점·선·면은 조형의 기본 요소, 리듬은 구성 원리." },
  { id: 601, conceptId: "form-element", category: "색채/디자인일반",
    question: "다음 중 디자인의 '구성 원리'에 해당하는 것은?",
    options: ["점", "선", "면", "균형"], answer: 3,
    explain: "균형·리듬·강조·통일은 구성 원리. 점·선·면은 기본 요소다." },

  { id: 7, conceptId: "golden-ratio", category: "색채/디자인일반",
    question: "황금비율의 근사값으로 옳은 것은?",
    options: ["1 : 1.414", "1 : 1.618", "1 : 2", "1 : 1.732"], answer: 1,
    explain: "황금비는 약 1 : 1.618. 1:1.414는 금속비(√2)." },

  // ===== HTML/CSS =====
  { id: 8, conceptId: "semantic-tag", category: "HTML/CSS",
    question: "HTML5에서 그 자체로 완결되는 독립 콘텐츠를 정의하는 시맨틱 태그는?",
    options: ["<div>", "<span>", "<article>", "<b>"], answer: 2,
    explain: "<article>은 독립적으로 배포·재사용 가능한 콘텐츠. div·span은 의미 없는 컨테이너." },
  { id: 801, conceptId: "semantic-tag", category: "HTML/CSS",
    question: "페이지의 가장 위에 위치하여 사이트 로고·메뉴를 담는 시맨틱 태그는?",
    options: ["<header>", "<footer>", "<section>", "<aside>"], answer: 0,
    explain: "<header>는 페이지·섹션의 머리말. <footer>는 꼬리말, <aside>는 부수 콘텐츠." },
  { id: 802, conceptId: "semantic-tag", category: "HTML/CSS",
    question: "사이트의 주된 탐색 링크 영역에 사용하는 시맨틱 태그는?",
    options: ["<menu>", "<nav>", "<list>", "<link>"], answer: 1,
    explain: "<nav>는 주요 탐색(navigation) 링크 영역을 의미한다." },

  { id: 9, conceptId: "img-alt", category: "HTML/CSS",
    question: "이미지를 표시할 수 없을 때 대체 텍스트를 제공해 웹 접근성을 높이는 <img> 속성은?",
    options: ["src", "alt", "title", "href"], answer: 1,
    explain: "alt 속성은 이미지 대체 텍스트로 스크린리더·접근성에 필수." },
  { id: 901, conceptId: "img-alt", category: "HTML/CSS",
    question: "다음 중 시각장애인을 위한 스크린리더가 이미지를 설명할 때 읽어주는 속성은?",
    options: ["src", "title", "alt", "name"], answer: 2,
    explain: "alt 속성의 텍스트가 스크린리더로 음성 안내된다." },

  { id: 10, conceptId: "doctype", category: "HTML/CSS",
    question: "HTML5 문서임을 선언하기 위해 문서 최상단에 작성하는 것은?",
    options: ["<meta>", "<!DOCTYPE html>", "<head>", "<title>"], answer: 1,
    explain: "<!DOCTYPE html>은 문서 형식 선언으로 맨 위에 작성." },

  { id: 11, conceptId: "box-model", category: "HTML/CSS",
    question: "CSS 박스 모델에서 콘텐츠와 테두리(border) 사이의 안쪽 여백은?",
    options: ["margin", "padding", "outline", "gap"], answer: 1,
    explain: "안쪽 여백은 padding, 테두리 바깥 여백은 margin." },
  { id: 1101, conceptId: "box-model", category: "HTML/CSS",
    question: "CSS 박스 모델에서 요소의 '테두리 바깥쪽' 여백을 지정하는 속성은?",
    options: ["margin", "padding", "border", "spacing"], answer: 0,
    explain: "margin은 요소와 다른 요소 사이의 바깥 여백." },
  { id: 1102, conceptId: "box-model", category: "HTML/CSS",
    question: "박스 모델 구성 요소를 안쪽부터 바깥쪽 순서로 올바르게 나열한 것은?",
    options: ["margin → border → padding → content", "content → padding → border → margin", "padding → content → margin → border", "content → margin → padding → border"], answer: 1,
    explain: "박스 모델: 콘텐츠 → 패딩(안쪽 여백) → 보더(테두리) → 마진(바깥 여백)." },

  { id: 12, conceptId: "specificity", category: "HTML/CSS",
    question: "CSS 선택자 중 명시도(우선순위)가 가장 높은 것은? (인라인 스타일 제외)",
    options: ["태그 선택자", "클래스 선택자", "id 선택자", "전체 선택자(*)"], answer: 2,
    explain: "명시도는 id > class > 태그 > 전체 순. 인라인 스타일은 그보다 높다." },
  { id: 1201, conceptId: "specificity", category: "HTML/CSS",
    question: "CSS에서 ID 선택자를 표시할 때 사용하는 기호는?",
    options: [".", "#", "*", "@"], answer: 1,
    explain: "ID는 #, 클래스는 ., 전체는 *. @는 @media 등 at-rule에 사용." },

  { id: 13, conceptId: "display-none", category: "HTML/CSS",
    question: "요소를 화면에서 숨기면서 차지하던 공간도 없애는 CSS 선언은?",
    options: ["visibility: hidden", "display: none", "opacity: 0", "position: absolute"], answer: 1,
    explain: "display:none은 공간까지 제거. visibility:hidden·opacity:0은 공간을 차지한다." },
  { id: 1301, conceptId: "display-none", category: "HTML/CSS",
    question: "다음 중 요소를 보이지 않게 하지만 '레이아웃 공간은 그대로 유지'하는 선언은?",
    options: ["display: none", "visibility: hidden", "remove()", "hidden=true"], answer: 1,
    explain: "visibility:hidden은 요소가 보이지 않지만 공간은 차지한다." },

  { id: 14, conceptId: "position", category: "HTML/CSS",
    question: "문서 흐름에서 벗어나 기준이 되는 부모 요소를 기준으로 배치되는 position 값은?",
    options: ["static", "relative", "absolute", "sticky"], answer: 2,
    explain: "absolute는 일반 흐름에서 빠져나와, position이 지정된 가장 가까운 조상 기준으로 배치." },
  { id: 1401, conceptId: "position", category: "HTML/CSS",
    question: "스크롤 시 일정 위치에서 고정되는 효과를 주는 position 값은?",
    options: ["fixed", "sticky", "absolute", "static"], answer: 1,
    explain: "sticky는 평소엔 일반 흐름, 임계점을 넘으면 고정된다. fixed는 항상 화면 기준 고정." },
  { id: 1402, conceptId: "position", category: "HTML/CSS",
    question: "스크롤과 무관하게 항상 브라우저 화면(뷰포트)에 고정되는 position 값은?",
    options: ["relative", "absolute", "fixed", "sticky"], answer: 2,
    explain: "fixed는 뷰포트 기준으로 항상 같은 자리에 고정된다." },

  // ===== JavaScript =====
  { id: 15, conceptId: "const-keyword", category: "JavaScript",
    question: "블록 스코프를 가지며 재할당이 불가능한 변수 선언 키워드는?",
    options: ["var", "let", "const", "new"], answer: 2,
    explain: "const는 블록 스코프·재할당 불가. let은 재할당 가능, var는 함수 스코프." },
  { id: 1501, conceptId: "const-keyword", category: "JavaScript",
    question: "다음 중 블록 스코프를 가지며 값을 다시 바꿀 수 있는 변수 선언 키워드는?",
    options: ["var", "let", "const", "static"], answer: 1,
    explain: "let은 블록 스코프이며 재할당이 가능하다." },
  { id: 1502, conceptId: "const-keyword", category: "JavaScript",
    question: "함수 스코프를 가지며 호이스팅 시 undefined로 초기화되는 옛 변수 키워드는?",
    options: ["var", "let", "const", "def"], answer: 0,
    explain: "var는 함수 스코프이며, 선언이 호이스팅되어 undefined로 초기화된다." },

  { id: 16, conceptId: "event", category: "JavaScript",
    question: "사용자의 클릭·입력 등 동작에 웹 페이지가 반응하도록 하는 것을 무엇이라 하는가?",
    options: ["이벤트", "메서드", "속성", "주석"], answer: 0,
    explain: "클릭·입력·로드 등 발생하는 동작을 이벤트라 하며, 이벤트 처리기로 반응 구현." },
  { id: 1601, conceptId: "event", category: "JavaScript",
    question: "버튼을 눌렀을 때 실행할 함수를 등록할 때 사용하는 메서드는?",
    options: ["addEventListener", "getElement", "querySelector", "createElement"], answer: 0,
    explain: "addEventListener('click', 함수) 형태로 이벤트와 동작을 연결한다." },

  // ===== UX/UI =====
  { id: 17, conceptId: "wireframe", category: "UX/UI",
    question: "화면 구성과 콘텐츠 배치를 선·도형으로 단순하게 표현한 설계 도면은?",
    options: ["스토리보드", "와이어프레임", "프로토타입", "무드보드"], answer: 1,
    explain: "와이어프레임은 레이아웃 골격을 단순한 선과 박스로 나타낸 설계도." },
  { id: 1701, conceptId: "wireframe", category: "UX/UI",
    question: "기획자·디자이너가 색·이미지 없이 화면 배치만 빠르게 그리는 산출물은?",
    options: ["프로토타입", "무드보드", "와이어프레임", "사이트맵"], answer: 2,
    explain: "와이어프레임은 색·이미지 없이 레이아웃 구조만 표현하는 설계 단계." },

  { id: 18, conceptId: "prototype", category: "UX/UI",
    question: "실제 동작에 가깝게 인터랙션을 구현해 사용성 테스트에 활용하는 산출물은?",
    options: ["사이트맵", "와이어프레임", "프로토타입", "스타일가이드"], answer: 2,
    explain: "프로토타입은 동작·전환을 구현해 실제 사용 흐름을 검증(사용성 테스트)하는 데 사용." },
  { id: 1801, conceptId: "prototype", category: "UX/UI",
    question: "다음 중 사용성 테스트(Usability Test)의 목적으로 가장 알맞은 것은?",
    options: ["서버 부하 측정", "사용자가 제품을 잘 쓰는지 검증", "코드 품질 점검", "디자인 색 선정"], answer: 1,
    explain: "사용성 테스트는 실제 사용자가 제품을 얼마나 쉽고 효과적으로 쓰는지 확인하는 과정." },

  { id: 19, conceptId: "ux-ui", category: "UX/UI",
    question: "사용자가 제품을 사용하며 느끼는 전반적인 경험을 의미하는 용어는?",
    options: ["UI", "UX", "GUI", "CLI"], answer: 1,
    explain: "UX(User Experience)는 사용 전반의 경험, UI는 화면·조작 인터페이스." },
  { id: 1901, conceptId: "ux-ui", category: "UX/UI",
    question: "버튼·메뉴·아이콘 등 사용자가 직접 보고 조작하는 화면 요소를 가리키는 용어는?",
    options: ["UX", "UI", "DB", "API"], answer: 1,
    explain: "UI(User Interface)는 사용자와 시스템이 만나는 화면·조작 영역." },

  // ===== 웹표준 =====
  { id: 20, conceptId: "w3c", category: "웹표준",
    question: "HTML·CSS 등 웹 표준과 웹 접근성 지침을 제정하는 국제 기구는?",
    options: ["ISO", "W3C", "IEEE", "ICANN"], answer: 1,
    explain: "W3C(World Wide Web Consortium)가 웹 표준과 WCAG 접근성 지침을 제정." },
  { id: 2001, conceptId: "w3c", category: "웹표준",
    question: "웹 접근성 국제 지침을 가리키는 약어는?",
    options: ["WCAG", "WAVE", "SEO", "ARIA"], answer: 0,
    explain: "WCAG(Web Content Accessibility Guidelines)는 W3C가 제정한 웹 접근성 지침." },
  { id: 2002, conceptId: "w3c", category: "웹표준",
    question: "도메인 이름과 IP 주소 관리(루트 DNS)를 담당하는 국제 기구는?",
    options: ["W3C", "ICANN", "IEEE", "ISO"], answer: 1,
    explain: "ICANN은 도메인·IP 자원 관리. W3C는 웹 표준 제정 기구." }
];

// 개념 ID → 카테고리/요약 빠른 매핑 (오답노트 표시용)
const CONCEPTS_INDEX = {
  "rgb-additive": "빛의 3원색과 가산혼합",
  "color-attr": "색의 3속성",
  "munsell": "먼셀 표색계 표기법",
  "contrast": "색의 대비 현상",
  "gestalt": "게슈탈트 시지각 원리",
  "form-element": "조형요소와 구성원리",
  "golden-ratio": "황금비율",
  "semantic-tag": "HTML5 시맨틱 태그",
  "img-alt": "이미지 alt 속성과 접근성",
  "doctype": "HTML5 문서 선언",
  "box-model": "CSS 박스 모델",
  "specificity": "CSS 선택자 명시도",
  "display-none": "요소 숨기기(display/visibility)",
  "position": "CSS position 속성",
  "const-keyword": "변수 선언 키워드(var/let/const)",
  "event": "이벤트와 이벤트 처리",
  "wireframe": "와이어프레임",
  "prototype": "프로토타입과 사용성 테스트",
  "ux-ui": "UX와 UI 차이",
  "w3c": "웹 표준 기구와 접근성"
};
